name: super_extensions
description: A package that supports most commonly used extension methods
version: 0.0.3
repository: 'https://github.com/AbhishekDoshi26/super_extensions'

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true