name: super_extensions
description: We probably use lots of extension methods in our project. So, this package combines all the extension methods that are used on daily basis and make them available to you under a single package so that you can reuse them in multiple packages.
version: 0.0.1
repository: 'https://github.com/AbhishekDoshi26/super_extensions'

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true