name: super_extensions
description: A package that supports most commonly used extension methods
version: 0.0.6
repository: 'https://github.com/AbhishekDoshi26/super_extensions'

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.4.2

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
